{
 "title": "Humidity",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Lower Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_humidity_percent{friendly_name=~\"Family Room Aqara Sensor Humidity|Humidor Sensor Humidity|Utility Room TuYa Sensor Humidity|Laundry Room Aqara Sensor Humidity\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Main Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_humidity_percent{friendly_name=~\"Garage Aqara Sensor Humidity|Kitchen Aqara Sensor Humidity|Living Room Aqara Sensor Humidity\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Upper Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_humidity_percent{friendly_name=~\"IBS-TH 09E9 Humidity|Emma’s Room Aqara Sensor Humidity|Master Bedroom TuYa Sensor Humidity|Liv’s Room Aqara Sensor Humidity\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}