{
 "title": "Temperatures",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Downstairs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(homeassistant_sensor_temperature_celsius{friendly_name=~\"Family Room Aqara Sensor Temperature\"})",
     "legendFormat": "Family Room"
    },
    {
     "expr": "avg(homeassistant_sensor_temperature_celsius{friendly_name=~\"Utility Room TuYa Sensor Temperature\"})",
     "legendFormat": "Utility Room"
    },
    {
     "expr": "avg(homeassistant_sensor_temperature_celsius{friendly_name=~\"Laundry Room Aqara Sensor Temperature\"})",
     "legendFormat": "Laundry Room"
    },
    {
     "expr": "avg(homeassistant_sensor_temperature_celsius{friendly_name=~\"Humidor Sensor Temperature\"})",
     "legendFormat": "Humidor"
    },
    {
     "expr": "avg(homeassistant_sensor_temperature_celsius{friendly_name=~\"Patio Propane Tank Temperature\"})",
     "legendFormat": "Patio"
    },
    {
     "expr": "avg(homeassistant_sensor_temperature_celsius{friendly_name=~\"Office.*\"})",
     "legendFormat": "Patio"
    }
   ]
  },
  {
   "title": "Living Room",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(friendly_name) (homeassistant_sensor_temperature_celsius{friendly_name=~\"Living Room Aqara Sensor Living Room Aqara Sensor temperature|Living Room Aqara Sensor Temperature\"})",
     "legendFormat": "Living Room"
    },
    {
     "expr": "avg by(friendly_name) (homeassistant_sensor_temperature_celsius{friendly_name=~\"Shelly Temperature\"})",
     "legendFormat": "Fireplace Shelly"
    },
    {
     "expr": "avg by(friendly_name) (homeassistant_sensor_temperature_celsius{friendly_name=~\"Deck Propane Tank Temperature\"})",
     "legendFormat": "Deck"
    },
    {
     "expr": "avg by(friendly_name) (homeassistant_sensor_temperature_celsius{friendly_name=~\"Kitchen Aqara Sensor Kitchen Aqara Sensor temperature|Kitchen Aqara Sensor Temperature\"})",
     "legendFormat": "Kitchen"
    },
    {
     "expr": "avg by(friendly_name) (homeassistant_sensor_temperature_celsius{friendly_name=~\"Garage Aqara Sensor Garage Aqara Sensor temperature|Garage Aqara Sensor Temperature\"})",
     "legendFormat": "Garage"
    }
   ]
  },
  {
   "title": "Upstairs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(friendly_name, entity) (homeassistant_sensor_temperature_celsius{friendly_name=~\"Emma’s Room Aqara Sensor Emma’s Room Aqara Sensor temperature|Liv’s Room Aqara Sensor Liv’s Room Aqara Sensor temperature|IBS-TH 09E9 Temperature|Master Bedroom TuYa Sensor Master Bedroom TuYa Sensor temperature|Fan and Lights device temperature|Ceiling Fan device temperature|Emma’s Room Aqara Sensor Temperature|Liv’s Room Aqara Sensor Temperature|Master Bedroom TuYa Sensor Temperature\"})",
     "legendFormat": "{{friendly_name}} {{entity}}"
    }
   ]
  }
 ]
}