repos:
  # Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      # Format Terraform files to canonical format
      - id: terraform_fmt

  # YAML/JSON validation and general code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Check YAML syntax
      - id: check-yaml
        args: ["--unsafe"] # Allow custom tags used by Kubernetes

      # Check JSON syntax
      - id: check-json

      # Ensure files end with newline
      - id: end-of-file-fixer

      # Trim trailing whitespace
      - id: trailing-whitespace

      # Prevent large files from being committed
      - id: check-added-large-files
        args: ["--maxkb=1000"]

      # Check for merge conflicts
      - id: check-merge-conflict

      # Detect private keys
      - id: detect-private-key
