apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: metallb-bgp-peer-to-udmp
  namespace: metallb-system
spec:
  myASN: 65001
  peerASN: 65000
  peerAddress: 172.16.0.1
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.1.0/24
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisement
  namespace: metallb-system