{
 "title": "NAS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(name) (ipmi_temperature_celsius{name=~\"CPU1 Temp|CPU2 Temp\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "avg by(name) (ipmi_fan_speed_rpm)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(name) (ipmi_temperature_celsius{name=~\"PCH Temp|System Temp|Peripheral Temp|GPU4 Temp\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(name) (ipmi_temperature_celsius{name=~\".*DIMM.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NIC Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(name) (ipmi_temperature_celsius{name=~\"MB_NIC_Temp2|MB_NIC_Temp1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRM Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(name) (ipmi_temperature_celsius{name=~\".*VRM.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg by(name) (ipmi_voltage_volts)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}