{
 "title": "Utility Measurements",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "UPS Battery Level",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(friendly_name) (homeassistant_sensor_battery_percent{entity=~\"sensor.myups_battery_charge\"})",
     "legendFormat": "UPS Battery Level"
    }
   ]
  },
  {
   "title": "UPS Voltages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_voltage_v{entity=~\"sensor.myups_input_voltage|sensor.myups_output_voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Radon Measurements",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pCi/L" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_pci_per_l{entity=~\"sensor.radoneye_rd200_radon|sensor.radoneye_rd200_radon_1_day_level|sensor.radoneye_rd200_radon_1_month_level\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Deck Propane Tank Level",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_distance_in{friendly_name=~\"Deck Propane Tank Tank Level|Patio Propane Tank Tank Level\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_carbon_dioxide_ppm{friendly_name=~\"Master Bedroom TuYa Sensor Master Bedroom TuYa Sensor co2|Utility Room TuYa Sensor Utility Room TuYa Sensor co2|Master Bedroom TuYa Sensor Carbon dioxide|Utility Room TuYa Sensor Carbon dioxide\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Formaldehyde",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_ppb{friendly_name=\"Master Bedroom TuYa Sensor Formaldehyd\"}",
     "legendFormat": "Main Bedroom"
    },
    {
     "expr": "(24.45 * homeassistant_sensor_unit_u0xb5g_per_mu0xb3{friendly_name=\"Utility Room TuYa Sensor Formaldehyd\"}) / 30.031",
     "legendFormat": "Utility Room"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_pm25_u0xb5g_per_mu0xb3{entity=~\"sensor.master_bedroom_tuya_sensor_pm25|sensor.utility_room_tuya_sensor_pm25|sensor.air_purifier_pm2_5\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_volatile_organic_compounds_parts_ppm{entity=~\"sensor.utility_room_tuya_sensor_voc|sensor.master_bedroom_tuya_sensor_voc\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  }
 ]
}