name: Terraform Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**/*.tf"
      - ".github/workflows/terraform-validation.yml"
  push:
    branches:
      - main
    paths:
      - "terraform/**/*.tf"
  workflow_dispatch:

jobs:
  discover-modules:
    name: Discover Terraform modules
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.find-modules.outputs.modules }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Terraform modules
        id: find-modules
        run: |
          # Find all directories containing terraform.tf files
          modules=$(find terraform -type f -name "terraform.tf" -exec dirname {} \; | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "modules=$modules" >> $GITHUB_OUTPUT
          echo "Found modules:"
          echo "$modules" | jq -r '.[]'

  validate-modules:
    name: Validate ${{ matrix.module }}
    runs-on: ubuntu-latest
    needs: discover-modules
    if: needs.discover-modules.outputs.modules != '[]'

    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.discover-modules.outputs.modules) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise and OpenTofu
        uses: jdx/mise-action@v2
        with:
          version: latest
          install: true
          cache: true

      - name: Create terraform alias for tofu
        run: |
          sudo ln -sf $(which tofu) /usr/local/bin/terraform
          terraform --version

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ${{ matrix.module }}
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend=false
        working-directory: ${{ matrix.module }}
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ matrix.module }}
        continue-on-error: true

      - name: Check results
        if: steps.fmt.outcome == 'failure' || steps.init.outcome == 'failure' || steps.validate.outcome == 'failure'
        run: |
          echo "::error::Validation failed for ${{ matrix.module }}"
          exit 1

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform
          format: sarif
          soft_fail: false
          additional_args: --config-file=.tfsec.yaml

      - name: Upload tfsec SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  lint:
    name: Terraform Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: "latest"

      - name: Initialize TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TFLint
        run: |
          # Run tflint on each Terraform directory
          find terraform -type f -name "terraform.tf" -exec dirname {} \; | sort -u | while read dir; do
            echo "Linting $dir..."
            tflint --config=.tflint.hcl --chdir="$dir" || exit 1
          done

  summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [validate-modules, security-scan, lint]
    if: always()

    steps:
      - name: Check validation results
        run: |
          if [[ "${{ needs.validate-modules.result }}" == "failure" || \
                "${{ needs.security-scan.result }}" == "failure" || \
                "${{ needs.lint.result }}" == "failure" ]]; then
            echo "::error::One or more validation checks failed"
            exit 1
          fi
          echo "✅ All Terraform validation checks passed!"
